name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub (or your container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username stored as a GitHub secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password stored as a GitHub secret

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-microservice:latest .

      # Step 4: Push the Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-microservice:latest



      
